set_property SRC_FILE_INFO {cfile:/home/locch/Documents/Zedboard/blink_vhdl/blink_vhdl.srcs/constrs_1/new/blink_vhdl_constraints.xdc rfile:../../../blink_vhdl.srcs/constrs_1/new/blink_vhdl_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports LD0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports SW0]
